### ISSUE TITLE
Fanspeed

### ISSUE THREAD

**Issue by Papercutter12** [merdok/homebridge-miot#22]
With the new Update (0.7.1) the fanspeed control is broken. Or rather the value of the fanspeed. The max fanspeed value was 100% before the update. Now it is 2200%. So its pretty annoying to control via siri.

**Comment by merdok** [comment]
You mean air purifiers, right? In the recent update i changed the relative % value to an absolute value reported by the fan. So it actually should be 2200rpm. I thought the slider control still works as a percentage value, but that is not the case you say?

**Comment by Papercutter12** [comment]
Yeah sorry i mean the airpurifier. The slider is still working normally but when using siri to change the fanspeed it uses the absolute value (2200rpm) as the %. So to get the airpurifier to 100% i have to say "hey siri set the air purifier to 2200%" .

**Comment by merdok** [comment]
Oh, that is of course not as it supposed to be... I thought i can get away with it without calculating the percentage by myself but i guess i have to do that.  I will adjust that in the next update to the behavior where slider is always in a 0-100% range.

**Comment by merdok** [comment]
Should be fixed in version 0.7.2

**Comment by firewhank** [comment]
Is this related? 
[homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -275 exceeded minimum of 0. See https://git.io/JtMGR for more info.

Updated from V0.7.0 to 0.7.2 and this starter to appear (I use an air purifier)

**Comment by merdok** [comment]
@firewhank which air purifier exactly (model)?

**Comment by firewhank** [comment]
@merdok Xiaomi Mi Air Purifier 3H Branco

**Comment by merdok** [comment]
@firewhank can you enable homebridge debug and post the log here when the error occurs? I would like to check what value the purifier has at that time.

**Comment by firewhank** [comment]
@merdok |

I think this might be what you need

5/2/2021, 10:31:04 AM] [homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -275 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/2/2021, 10:31:04 AM] [homebridge-miot] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at RotationSpeed.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AirPurifierAccessory.updateDeviceStatus (/homebridge/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:249:150)
    at MiotController.<anonymous> (/homebridge/node_modules/homebridge-miot/index.js:123:33)
    at MiotController.emit (events.js:315:20)
    at /homebridge/node_modules/homebridge-miot/lib/MiotController.js:102:14
[5/2/2021, 10:31:09 AM] [homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -275 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[5/2/2021, 10:31:09 AM] [homebridge-miot] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at RotationSpeed.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at AirPurifierAccessory.updateDeviceStatus (/homebridge/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:249:150)
    at MiotController.<anonymous> (/homebridge/node_modules/homebridge-miot/index.js:123:33)
    at MiotController.emit (events.js:315:20)
    at /homebridge/node_modules/homebridge-miot/lib/MiotController.js:102:14

**Comment by merdok** [comment]
@firewhank before that there should be a list of properties which was updated in the log (please note debug log needs to be enabled), i would need to see that list as well to compare what the actual value from the purifier is.

**Comment by firewhank** [comment]
@merdok

**Comment by merdok** [comment]
@firewhank now you posted the initialization which does not help me. 
You need to look for the error in the console and just before the error a "Properties updated" message with a list of updated properties will be in the console. I need that list!

**Comment by firewhank** [comment]
@merdok 

Sorry but I have the log´s activated in the homebridge settings and I don’t have “properties updated” in the log

Maybe this? 
[5/2/2021, 10:46:41 AM] [miot] [Mi Air Purifier] Got initial device properties: 
 [
  {
    "name": "power",
    "value": false
  },
  {
    "name": "fan_level",
    "value": 2
  },
  {
    "name": "mode",
    "value": 2
  },
  {
    "name": "favorite_speed",
    "value": 880
  },
  {
    "name": "child_lock",
    "value": false
  },
  {
    "name": "led",
    "value": 0
  },
  {
    "name": "alarm",
    "value": false
  },
  {
    "name": "pm25_density",
    "value": 1
  },
  {
    "name": "relative_humidity",
    "value": 57
  },
  {
    "name": "temperature",
    "value": 18
  },
  {
    "name": "filter_life_level",
    "value": 79
  },
  {
    "name": "filter_used_time",
    "value": 726
  },
  {
    "name": "fan_speed_rpm",
    "value": 0
  },
  {
    "name": "use_time",
    "value": 2537100
  },
  {
    "name": "aqi_state",
    "value": 0
  },
  {
    "name": "aqi_value",
    "value": 15
  }
]

**Comment by merdok** [comment]
@firewhank this is better but still not what i need. The list as above will be exactly the same but i need the list which comes directly before the error appears as i need to see the exact value reported by the air purifier. You need to enable homebridge debug log for that and set the `deepDebugLog` property to true in the config.json

**Comment by jipvankuijk** [comment]
Hey @merdok 

When I say “Hey Siri set the Air Purifier to 20%” it say “Okay I’ve set the Air Purifier to 9%” but the slider goes to 100% and the fan blasts like crazy. 

When I adjust the slider itself it works as expected.

Happy to get you logs if needed.

**Comment by merdok** [comment]
@jipvankuijk 
This should be fixed in version 0.7.2

**Comment by 3dmaster90** [comment]
same issue for me in the latest update.

[homebridge-miot] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number -275 exceeded minimum of 0. See https://git.io/JtMGR for more info.

i´m using an Mi Air Purifier 3C

**Comment by merdok** [comment]
@3dmaster90 i would need a little bit more context so you would need to post some more debug log with deepDebugLog enabled here. I need to see what properties are actually set so you need to post some log which directly appears before the warning.
