### ISSUE TITLE
Issue with action button

### ISSUE THREAD

**Issue by lucaesse** [merdok/homebridge-miot#30]
If I add an action button I get this error:
 ReferenceError: tmpActionName is not defined
    at /usr/local/lib/node_modules/homebridge-miot/lib/base/BaseAccessory.js:287:82
    at Array.filter (<anonymous>)
    at RobotCleanerAccessory.prepareActionButtonServices (/usr/local/lib/node_modules/homebridge-miot/lib/base/BaseAccessory.js:287:38)
    at RobotCleanerAccessory.setupAdditionalAccessoryServices (/usr/local/lib/node_modules/homebridge-miot/lib/modules/robotcleaner/RobotCleanerAccessory.js:57:34)
    at new BaseAccessory (/usr/local/lib/node_modules/homebridge-miot/lib/base/BaseAccessory.js:49:12)
    at new RobotCleanerAccessory (/usr/local/lib/node_modules/homebridge-miot/lib/modules/robotcleaner/RobotCleanerAccessory.js:9:5)
    at Function.createAccessory (/usr/local/lib/node_modules/homebridge-miot/lib/AccessoryFactory.js:52:24)
    at xiaomiMiotDevice.initAccessory (/usr/local/lib/node_modules/homebridge-miot/index.js:138:48)
    at MiotController.<anonymous> (/usr/local/lib/node_modules/homebridge-miot/index.js:99:14)
    at MiotController.emit (events.js:315:20)

---
Homebridge continuously restart.

My config is:
        {
            "devices": [
                {
                    "name": "Britney",
                    "ip": "192.168.3.81",
                    "token": "3447675969616a485945674239794d6c",
                    "pollingInterval": 5,
                    "deepDebugLog": false,
                    "actionButtons": [
                        {
                            "action": "locate_robot",
                            "name": "Trova"
                        }
                    ]
                }
            ],
            "platform": "miot"
        }

Everything works fine without custom action button.

**Comment by merdok** [comment]
Oh, i see the issue. I made a typo in the code... Will fix that in the next update and let you when it is released!
Thanks for reporting!

**Comment by lucaesse** [comment]
> Oh, i see the issue. I made a typo in the code... Will fix that in the next update and let you when it is released!
> Thanks for reporting!

Thank you!

**Comment by merdok** [comment]
Should be fixed in version 0.8.2. Could you please try it out and let me know if it works now?

**Comment by lucaesse** [comment]
> Should be fixed in version 0.8.2. Could you please try it out and let me know if it works now?

Works like a charm! Thank you!
