### ISSUE TITLE
Xiaomi Dehumidifier Control

### ISSUE THREAD

**Issue by chrhee21** [merdok/homebridge-miot#313]
I am using dmaker.derh.22l.
Everything is OK except dehumidification set value. 
Even though set value of machine itself is 60 %,  set value appears as 75% in Home app.
If I adjust set value as 60% through Home app, set value of machine adjusted as 54%. 
There is difference between Home app set value and machine set value. 

Thank you.

**Comment by merdok** [comment]
Might be that some calculations are being done wrong. Can you maybe please post a homebridge debug log from the setup and when you try to control the value?

**Comment by chrhee21** [comment]
I am sorry for my late reply. 
I am not familiar with coding.
What I can get from log is below. 

[05/08/2022, 23:02:50] [miot] [샤오미 제습기] Device setup finished! Miot device ready!
[05/08/2022, 23:02:50] [miot] [샤오미 제습기] Connected to device: dmaker.derh.22l
[05/08/2022, 23:02:51] [homebridge-miot] This plugin generated a warning from the characteristic 'Relative Humidity Dehumidifier Threshold': characteristic was supplied illegal value: number 0 exceeded minimum of 30. See https://homebridge.io/w/JtMGR for more info.
[05/08/2022, 23:02:51] [homebridge-miot] Error: 
    at RelativeHumidityDehumidifierThreshold.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at RelativeHumidityDehumidifierThreshold.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:2045:14)
    at RelativeHumidityDehumidifierThreshold.Characteristic.updateValue (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at DehumidifierAccessory.updateAccessoryStatus (/var/lib/homebridge/node_modules/.pnpm/homebridge-miot@1.2.4/node_modules/homebridge-miot/lib/modules/dehumidifier/DehumidifierAccessory.js:166:132)
    at DehumidifierDevice.updateAccessoryStatus (/var/lib/homebridge/node_modules/.pnpm/homebridge-miot@1.2.4/node_modules/homebridge-miot/lib/base/BaseDevice.js:227:54)
    at MiotDevice.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-miot@1.2.4/node_modules/homebridge-miot/lib/base/BaseDevice.js:66:12)
    at MiotDevice.emit (node:events:539:35)
    at MiotDevice._deviceFound (/var/lib/homebridge/node_modules/.pnpm/homebridge-miot@1.2.4/node_modules/homebridge-miot/lib/protocol/MiotDevice.js:283:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I am not sure this information is helpful or not.
On the dehumidifier itself, adjustable humidity range is from 40 to 70%. 
But, in HomeKit, adjustable humidity range is from 0 to 100%. 

I always thank you for your kindness. 
Best regards.

**Comment by merdok** [comment]
Based on the miot spec of your device the target humidity range is 30% to 70%. 

Besides you would need to provide some homebridge debug log so i can see what the device is reporting. Check here https://github.com/merdok/homebridge-miot#troubleshooting to see on how to start homerbidge in debug mode.
