### ISSUE TITLE
Support for air conditioner partner and outlet

### ISSUE THREAD

**Issue by randomActual** [merdok/homebridge-miot#42]
I have  lumi.aircondition.acn05 and cuco.plug.cp2, can add support for these devices?

Thanks you so much!

**Comment by merdok** [comment]
Hello,
yes that should be no problem! I will add support for both devices on the next update!

**Comment by merdok** [comment]
Both added in version 0.9.4. Please try it out and let me know if everything works.

**Comment by randomActual** [comment]
When i upgraded to 0.9.4, homebridge cannot run.

I have a dmaker.fan.p11, it can run in 0.9.3.

The system log is :

 ReferenceError: CurtainProperties is not defined
    at DmakerFanP11.initDeviceProperties (/homebridge/node_modules/homebridge-miot/lib/modules/fan/devices/dmaker.fan.p11.js:79:22)
    at DmakerFanP11._initDevice (/homebridge/node_modules/homebridge-miot/lib/protocol/MiotDevice.js:61:10)
    at new MiotDevice (/homebridge/node_modules/homebridge-miot/lib/protocol/MiotDevice.js:52:10)
    at new BaseDevice (/homebridge/node_modules/homebridge-miot/lib/base/BaseDevice.js:13:5)
    at new FanDevice (/homebridge/node_modules/homebridge-miot/lib/modules/fan/FanDevice.js:9:5)
    at new DmakerFanP11 (/homebridge/node_modules/homebridge-miot/lib/modules/fan/devices/dmaker.fan.p11.js:15:5)
    at Function.createDevice (/homebridge/node_modules/homebridge-miot/lib/DeviceFactory.js:97:22)
    at MiotController._createMiotDevice (/homebridge/node_modules/homebridge-miot/lib/MiotController.js:81:39)
    at MiotController.connectToDevice (/homebridge/node_modules/homebridge-miot/lib/MiotController.js:41:12)
    at xiaomiMiotDevice.initMiotController (/homebridge/node_modules/homebridge-miot/index.js:100:25)

**Comment by merdok** [comment]
Oh, sorry for that. It was a small typo from my side. Should now be fixed in version 0.9.5. Please try it out.
