### ISSUE TITLE
Device has no identifier yet, handshake needed

### ISSUE THREAD

**Issue by blastoma** [merdok/homebridge-miot#56]
Hello!

Last three releases I see error in first start of plugin:
[05/07/2021, 17:07:20] [homebridge-miot] [Бризер] Accessory successfully initialized!
Starting to advertise 'homebridge-miot 412B' using bonjour-hap backend!
[05/07/2021, 17:07:21] Homebridge v1.3.4 (homebridge-miot) is running on port 43069.

/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:273
                        throw new Error('Device has no identifier yet, handshake needed');
         ^
Error: Device has no identifier yet, handshake needed
    at DeviceInfo.enrich (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:273:10)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:165:13)
    at Socket.emit (events.js:375:28)
    at UDP.onMessage (dgram.js:941:8)
[05/07/2021, 17:07:22] [homebridge-miot] Child bridge process ended
[05/07/2021, 17:07:22] [homebridge-miot] Process Ended. Code: 1, Signal: null
[05/07/2021, 17:07:29] [homebridge-miot] Restarting Process...

After "Restarting Process" there is no error and plugin starts well

**Comment by merdok** [comment]
Hi,

Looks like an error from the dependency library which is used, i do not think that it has anything to do with the plugin itself. I would suspect that something is wrong in your network, maybe firewall, high latency or packets drops?
You can try to start homebridge in debug mode to check if there is anything additional besides i do not think there is anything that i can do...

**Comment by blastoma** [comment]
Debug mode On:
[05/07/2021, 18:28:55] [homebridge-miot] [Бризер] Error: Could not connect to device, handshake timeout
[05/07/2021, 18:28:55] [homebridge-miot] [Бризер] Could not connect to the device! Retrying in 18 seconds!
[05/07/2021, 18:28:55] [homebridge-miot] [Пылесос] Splitting properties into chunks. Number of chunks: 2. Chunk size: 14

/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:273
                        throw new Error('Device has no identifier yet, handshake needed');
         ^
Error: Device has no identifier yet, handshake needed
    at DeviceInfo.enrich (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:273:10)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/network.js:165:13)
    at Socket.emit (events.js:375:28)
    at UDP.onMessage (dgram.js:941:8)
[05/07/2021, 18:28:55] [homebridge-miot] Child bridge process ended
[05/07/2021, 18:28:55] [homebridge-miot] Process Ended. Code: 1, Signal: null

**Comment by merdok** [comment]
Yes, this confirms that the error originates in the dependency and not in the plugin, so there is really nothing i can do.
But as for me the error does not appear, i am pretty certain that it has something to do with your local setup rather then the dependency, so you would need to investigate what is causing the error for you.

**Comment by blastoma** [comment]
Okey, thank you!
