### ISSUE TITLE
Xiaomi Air Purifier 3C: "Device not supported! Using a generic device with limited properties!"

### ISSUE THREAD

**Issue by kaiserkiwi** [merdok/homebridge-miot#6]
Sadly the new Purifier 3C isn't supported yet. Even worse: My Bridge completely shuts down, if I try to activate the Plugin with my Device.

I hope this can be fixed soon.

**Comment by kaiserkiwi** [comment]
Some additional info. This is the complete Log for this.

```
22.3.2021, 16:14:24 [miot] Initializing devices
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Got device configuration, initializing device with name: Xiaomi Air Purifier
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Device model known: XiaomiAirPurifier3! Creating device!
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Initializing device properties
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Initializing device capabilities
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Device not supported! Using a generic device with limited properties! Consider requesting device support!
22.3.2021, 16:14:24 [miot] [Xiaomi Air Purifier] Initializing accessory!
22.3.2021, 16:14:24 TypeError: this.powerSwitchService.getCharacteristic(...).onGet is not a function
    at GenericAccessory.prepareSwitchService (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/generic/GenericAccessory.js:64:8)
    at GenericAccessory.setupAccessoryServices (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/generic/GenericAccessory.js:54:10)
    at GenericAccessory.initAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/generic/GenericAccessory.js:49:10)
    at new GenericAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/generic/GenericAccessory.js:35:10)
    at Function.createAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/AccessoryFactory.js:42:24)
    at xiaomiMiotDevice.initAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:136:47)
    at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:97:14)
    at MiotController.emit (events.js:315:20)
    at MiotController.createMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:91:14)
    at MiotController.connectToDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:38:12)
    at xiaomiMiotDevice.initMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:125:25)
    at new xiaomiMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:82:10)
    at miotPlatform.initDevices (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:236:11)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:212:14)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
22.3.2021, 16:14:24 Got SIGTERM, shutting down Bridge...
```

**Comment by merdok** [comment]
Can you post your config?

It seems that you put a wrong value in the "model" property. You should not put anything there unless you are sure what your device model is!
