### ISSUE TITLE
Error: send ENETUNREACH 224.0.0.251:5353

### ISSUE THREAD

**Issue by blu-e-man** [merdok/homebridge-miot#60]
Hi, I have installed the latest version from Homebridge (Docker) and from Homebridge-miot.
For some time now, the Homebridge shuts down and restarts.
These errors are then visible in the log.

```
[7/6/2021, 10:35:20 PM] [miot] [MIVentilator] Device setup finished! Device ready, you can now control your device!
[7/7/2021, 12:31:25 AM] Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:714:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:435:18)
    at afterDns (dgram.js:660:5)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
[7/7/2021, 12:31:25 AM] Got SIGTERM, shutting down Homebridge...

[MIVentilator] Device setup finished! Device ready, you can now control your device!
[7/9/2021, 1:50:32 PM] Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (dgram.js:714:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:435:18)
    at afterDns (dgram.js:660:5)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
[7/9/2021, 1:50:32 PM] Got SIGTERM, shutting down Homebridge...

[miot] [MIVentilator] Device setup finished! Device ready, you can now control your device!
[7/9/2021, 1:52:46 PM] Error: Device has no identifier yet, handshake needed
    at DeviceInfo.enrich (/homebridge/node_modules/homebridge-miot/node_modules/miio/lib/network.js:273:10)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-miot/node_modules/miio/lib/network.js:165:13)
    at Socket.emit (events.js:375:28)
    at UDP.onMessage (dgram.js:941:8)
[7/9/2021, 1:52:46 PM] Got SIGTERM, shutting down Homebridge...



```

**Comment by merdok** [comment]
Looks like the ip you specified there cannot be reached, this looks to me like a network issue. Maybe the docker container is in a different subnetwork?

**Comment by blu-e-man** [comment]
Thank you for your answer.
The Docker container and devices are all on the same subnet.

**Comment by merdok** [comment]
Well the error clearly states that an ip cannot be reached, not sure from what the ip is but you need to investigate why it cannot be reached.

**Comment by blu-e-man** [comment]
All right, thank you.
