### ISSUE TITLE
deerma.humidifier.jsq4  Water Level Temperature Humidity is wrong

### ISSUE THREAD

**Issue by louliangsheng** [merdok/homebridge-miot#79]
This plugin generated a warning from the characteristic 'Water Level': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

Temperature and Humidity No value
![image](https://user-images.githubusercontent.com/37586254/131255733-168bf2fb-5116-45e5-b263-fd78a125e19e.png)

**Comment by louliangsheng** [comment]
buzzerControl and ledControl not work

**Comment by merdok** [comment]
@louliangsheng could you please provide some homebridge debug log? I would like to identify from where exactly the warning originate.

**Comment by louliangsheng** [comment]
[30/08/2021, 17:46:26] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property led. Response: {"did":"338228296","siid":3,"piid":6,"code":3}
[30/08/2021, 17:46:26] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property alarm. Response: {"did":"338228296","siid":3,"piid":5,"code":-4004}
[30/08/2021, 17:46:26] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property relative_humidity. Response: {"did":"338228296","siid":3,"piid":1,"code":-4004}
[30/08/2021, 17:46:26] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property temperature. Response: {"did":"338228296","siid":3,"piid":7,"code":-4004}
[30/08/2021, 17:46:26] [homebridge-miot] [纯净式加湿器] The property water_level was not found on this deivce!
[30/08/2021, 17:46:26] [homebridge-miot] This plugin generated a warning from the characteristic 'Water Level': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

**Comment by louliangsheng** [comment]
Is this debug log?

**Comment by louliangsheng** [comment]
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property led. Response: {"did":"338228296","siid":3,"piid":6,"code":3}
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property alarm. Response: {"did":"338228296","siid":3,"piid":5,"code":-4004}
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property relative_humidity. Response: {"did":"338228296","siid":3,"piid":1,"code":-4004}
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] Error while parsing response from device for property temperature. Response: {"did":"338228296","siid":3,"piid":7,"code":-4004}
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] The property water_level was not found on this deivce!
[30/08/2021, 17:47:46] [homebridge-miot] This plugin generated a warning from the characteristic 'Water Level': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.
[30/08/2021, 17:47:46] [homebridge-miot] Error: 
    at WaterLevel.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at WaterLevel.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1891:14)
    at WaterLevel.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1379:20)
    at HumidifierAccessory.updateDeviceStatus (/usr/local/lib/node_modules/homebridge-miot/lib/modules/humidifier/HumidifierAccessory.js:209:101)
    at DeermaHumidifierJsq4.<anonymous> (/usr/local/lib/node_modules/homebridge-miot/index.js:132:33)
    at DeermaHumidifierJsq4.emit (events.js:375:28)
    at /usr/local/lib/node_modules/homebridge-miot/lib/protocol/MiotDevice.js:232:14
[30/08/2021, 17:47:46] [homebridge-miot] [纯净式加湿器] Device properties updated: 
 [
  {
    "name": "power",
    "value": false
  },
  {
    "name": "fan_level",
    "value": 3
  },
  {
    "name": "target_humidity",
    "value": 59
  },
  {
    "name": "led",
    "value": false
  },
  {
    "name": "alarm",
    "value": false
  },
  {
    "name": "relative_humidity",
    "value": 0
  },
  {
    "name": "temperature",
    "value": 0
  }
]

**Comment by louliangsheng** [comment]
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "power": false -> 0
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "power": false -> 0
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "fan_level": 3 -> 3
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "water_level": false -> 80
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "relative_humidity": 73 -> 73
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "relative_humidity": 73 -> 73
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "switch_status": true -> true
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "target_humidity": 59 -> 59
[30/08/2021, 17:53:24] [homebridge-mi-humidifier] [192.168.123.121] Updating property "buzzer": false -> false


This is another plugin. It works

**Comment by merdok** [comment]
Thanks! Can you also please post your config.json entry?

**Comment by louliangsheng** [comment]
{
                    "name": "纯净式加湿器",
                    "ip": "192.168.123.121",
                    "token": "a14dcf7f5003ec95fd0388a218e573ee",
                    "deviceId": "338228296",
                    "model": "deerma.humidifier.jsq4",
                    "pollingInterval": 5,
                    "deepDebugLog": true,
                    "buzzerControl": false,
                    "ledControl": false,
                    "Water_Level": false,
                    "fanLevelControl": true,
                    "screenControl": false,
                    "dryControl": false
                }

Marcin ***@***.***> 于 2021年8月30日周一 18:12写道：

**Comment by louliangsheng** [comment]
[homebridge-mi-humidifier] [192.168.123.121] Fail to get device properties. SocketError: Timeout

Another plugin has this error, so I will try your plugin. I have another suggestion for your plugin. You can provide a renaming function in homebridge so that I don’t need to rename it in homekit.

**Comment by merdok** [comment]
In your config "Water_Level" - this configuration property does not exist! Please check the README for available configuration fields!

**Comment by louliangsheng** [comment]
I know it does not exist, it is added by myself, I just want to see if adding "Water_Level" will be useful. The "Water_Level" in my config is not the point.

**Comment by louliangsheng** [comment]
Because it does not exist, I add it does not affect the work of the plugin.

**Comment by merdok** [comment]
Yes, but it causes a warning in your log. I will check put the other issues and see if I can provide a fix!

**Comment by louliangsheng** [comment]
I checked other issues and found that you are a very enthusiastic developer. I noticed that others are very polite. I recalled my issue and felt that there was a problem with the tone of my question. My English is not very good ( I know you are a German, should I translate it into German), I am talking to you through Google Translate, you can answer my issue, I am very honored, thank you.

我查看了其他的问题 ，发现您是一个非常热心的开发者，我察觉到其他人都非常有礼貌，我回想了一下自己的问题，觉得自己提问语气有些问题，我的英语并不太好（我知道您是个德国人，我是不是该翻译成德语），我是通过谷歌翻译与您对话，您能回答我这个问题，我已经非常荣幸，谢谢您。

**Comment by louliangsheng** [comment]
> Yes, but it causes a warning in your log. I will check put the other issues and see if I can provide a fix!

I did not add it before there will be a warning

**Comment by merdok** [comment]
Yes, no worries 😌 I will have a look at the warnings and issues and will see if I can fix them!

**Comment by louliangsheng** [comment]
Thank you very much, I now refer to the devices in your plugin and which devices I buy.

**Comment by louliangsheng** [comment]
Thank you very much, now the humidifier is working perfectly. But I have a little suggestion. In Mihome App, the constant humidity mode range is 40%-70%, but the humidity level in your plug-in is 0-100%, which is not corresponding.

**Comment by merdok** [comment]
0-100% humidity range is what the humidifier reports so i show the whole range. The miHome app often limits or hides some things...
