### ISSUE TITLE
Device doesn't show up

### ISSUE THREAD

**Issue by kaiserkiwi** [merdok/homebridge-miot#9]
I successfully added my Air Purifier 3C to the Plugin, bit it doesn't show up in my devices. It's not unassigned or something, it's just not there. I also can't find it in my home app. But according to the logs everything seems fine

![image](https://user-images.githubusercontent.com/8428551/113107437-3912f400-9204-11eb-9e42-47aaebd665c1.png)

My Device setup looks like this:
```
[
    {
        "name": "Xiaomi Air Purifier",
        "ip": "REDACTED",
        "token": "REDACTED",
        "pollingInterval": 5,
        "fanLevelControl": true,
        "modeControl": true
    }
]
```

**Comment by merdok** [comment]
Hmmm, log looks ok at first sight. Could you also post a homebridge debug log so I can see if there is something wrong?

Did you also try to check if the device is available in the homebridge ui?

**Comment by kaiserkiwi** [comment]
Sorry I wasn't on my computer for a while.
Just tried to reboot my Homebridge to get a fresh Debug.
Now I get the following error:
```
6.4.2021, 13:48:09 [miot] Initializing devices
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Got device configuration, initializing device with name: Xiaomi Air Purifier
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Device model known: zhimi.airpurifier.mb4! Creating device!
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Initializing device properties
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Initializing device capabilities
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Device successfully created! It is a AirPurifier device!
6.4.2021, 13:48:09 [miot] [Xiaomi Air Purifier] Initializing accessory!
6.4.2021, 13:48:09 TypeError: this.airPurifierService.getCharacteristic(...).onGet is not a function
    at AirPurifierAccessory.prepareAccessoryService (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:71:8)
    at AirPurifierAccessory.setupAccessoryServices (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:55:10)
    at new AirPurifierAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/modules/airpurifier/AirPurifierAccessory.js:41:10)
    at Function.createAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/AccessoryFactory.js:42:24)
    at xiaomiMiotDevice.initAccessory (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:138:47)
    at MiotController.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:99:14)
    at MiotController.emit (events.js:315:20)
    at MiotController.createMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:90:14)
    at MiotController.connectToDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/lib/MiotController.js:37:12)
    at xiaomiMiotDevice.initMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:127:25)
    at new xiaomiMiotDevice (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:84:10)
    at miotPlatform.initDevices (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:238:11)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-miot/index.js:214:14)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
6.4.2021, 13:48:09 Got SIGTERM, shutting down Bridge...
```

I've updated to the newest version already. My config didn't change since my last post.

**Comment by merdok** [comment]
Homebridge version at least 1.3.0 is required and from the log it seems that you have an older version. You need to update your homebridge.

**Comment by kaiserkiwi** [comment]
You're right. My HOOBS wasn't up to date. Thanks for you support. It now shows up!
