### ISSUE TITLE
Please add support for the  Xiaomi Chuangmi Plug V1 (chuangmi.plug.v1)

### ISSUE THREAD

**Issue by oleg77s** [merdok/homebridge-miot#91]
Please add support for the  Xiaomi Chuangmi Plug V1 (with one USB):
Model: chuangmi.plug.v1
Region: cn

**Comment by merdok** [comment]
Support for this device will be added in the next update. Please note that this is an older miio device which will require MiCloud

**Comment by oleg77s** [comment]
Unfortunately, Plug v1 is not controlled in HK: No Response.
logs:
[16/10/2021, 12:04:14] [miot] Found cached accessory Plug_v1
[16/10/2021, 12:04:14] [miot] Found cached accessory Smartmi Ventilation System
[16/10/2021, 12:04:14] [miot] Removing all cached accessories
[16/10/2021, 12:04:14] [miot] Initializing devices
[16/10/2021, 12:04:14] [miot] [Plug_v1] Got device configuration, initializing device with name: Plug_v1
[16/10/2021, 12:04:14] [miot] [Plug_v1] Device info file does not exist yet!
[16/10/2021, 12:04:14] [miot] [Plug_v1] Device model known: chuangmi.plug.v1! Creating device!
[16/10/2021, 12:04:15] [miot] [Plug_v1] Creating miot device!
[16/10/2021, 12:04:15] [miot] [Plug_v1] Device Factory - Creating device instance by model: chuangmi.plug.v1!
[16/10/2021, 12:04:15] [miot] [Plug_v1] Initializing device properties
[16/10/2021, 12:04:15] [miot] [Plug_v1] Device properties: [
  "power",
  "usb_power"
]
[16/10/2021, 12:04:15] [miot] [Plug_v1] Initializing device actions
[16/10/2021, 12:04:15] [miot] [Plug_v1] Successfully created a Outlet device! It is a Xiaomi Chuangmi Plug V1.
[16/10/2021, 12:04:15] [miot] [Plug_v1] Initializing accessory!
[16/10/2021, 12:04:15] [miot] [Plug_v1] Accessory Factory - Creating Outlet accessory for device Plug_v1!
[16/10/2021, 12:04:15] [miot] [Plug_v1] Accessory successfully initialized!

[16/10/2021, 12:07:05] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 12:07:05] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
........................................

 "name": "Plug_v1",
                    "ip": "192.168.0.239",
                    "token": "---------------",
                    "deviceId": "11425250",
                    "model": "chuangmi.plug.v1",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "username": "1581------",
                        "password": "-------",
                        "forceMiCloud": true,
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": true

**Comment by merdok** [comment]
Oh, there seems to be some kind of error. You would need to enable homebridge debug log and post the debug log here so i can check if i can find from where the error originates.

**Comment by oleg77s** [comment]
Homeridge debut log -D was enabled

**Comment by oleg77s** [comment]
[16/10/2021, 14:21:55] Loading 2 platforms...
[16/10/2021, 14:21:55] [Config] Initializing config platform...
[16/10/2021, 14:21:55] [Config] Running in Service Mode
[16/10/2021, 14:21:55] [miot] Initializing miot platform...
[16/10/2021, 14:21:55] [miot] Removing all cached accessories
[16/10/2021, 14:21:56] [miot] Initializing devices
[16/10/2021, 14:21:56] [miot] [Plug_v1] Got device configuration, initializing device with name: Plug_v1
[16/10/2021, 14:21:56] [miot] [Plug_v1] Device info file does not exist yet!
[16/10/2021, 14:21:56] [miot] [Plug_v1] Device model unknown! Starting discovery!
Preparing Advertiser for 'Homebridge Harmony 3F95' using bonjour-hap backend!
Setup Payload:
X-HM://0024MWWBTLK53
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 705-13-065 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge Harmony 3F95' using bonjour-hap backend!
[16/10/2021, 14:21:56] Homebridge v1.3.4 (Homebridge Harmony) is running on port 51873.
[16/10/2021, 14:21:56] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:21:56] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
[16/10/2021, 14:22:38] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:22:38] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
[16/10/2021, 14:23:20] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:23:20] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
[16/10/2021, 14:24:03] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:24:03] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
[16/10/2021, 14:24:45] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:24:45] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!
[16/10/2021, 14:25:27] [miot] [Plug_v1] TypeError: this.addChild is not a function
[16/10/2021, 14:25:27] [miot] [Plug_v1] Could not connect to the device! Retrying in 42 seconds!


"devices": [
                {
                    "name": "Plug_v1",
                    "ip": "192.168.0.239",
                    "token": "6ac7354a14c15eab50a71c6fea36b7ca",
                    "deviceId": "11425250",
                    "model": "",
                    "pollingInterval": 7,
                    "deepDebugLog": true,
                    "micloud": {
                        "username": "1581522456",
                        "password": "123gelo7",
                        "country": "cn",
                        "forceMiCloud": true,
                        "timeout": 5000
                    },
                    "buzzerControl": false,
                    "ledControl": true

**Comment by oleg77s** [comment]
only Plug v1 doesn't work, m1 and v3 working

**Comment by merdok** [comment]
Does not matter, the error comes from somewhere in your environment. It does not seems like it has anything to do with the plugin itself since when i try it out with the Plug v1 then i have no errors like in your case. Not sure from where it comes.

**Comment by oleg77s** [comment]
Where in RPI SD card can I find it?

**Comment by oleg77s** [comment]
found in usr/local/lib/node_modules/

**Comment by oleg77s** [comment]
Starting to advertise 'Homebridge DD58 18B7' using bonjour-hap backend!
[16/10/2021, 21:40:21] Homebridge v1.3.5 (Homebridge DD58) is running on port 51252.
(node:1484) UnhandledPromiseRejectionWarning: TypeError: this.addChild is not a function
    at new module.exports (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/devices/chuangmi.plug.v1.js:21:8)
    at /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/connectToDevice.js:25:12
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by merdok** [comment]
Oh, it seems like the miio library has already a file for that device which causes the crash. Somehow the library detects that it has support for your device and tries to do something which causes the crash. Not sure I will be able to somehow fix that...

**Comment by oleg77s** [comment]
Hmm, why you  have no errors  with plug v1?

**Comment by merdok** [comment]
Because i do not have the plug v1 and i can only test if there are errors during initialization, the error which you have on the other hand happens during connection... Like i already said the error does not happen in my plugin but in a dependency so i am not sure if i will be able to do anything. 
I mean you could go to the miio `node_modules` under homebridge-miot and then to lib->devices and delete the `chuangmi.plug.v1.js` there locally, that should at least be a temporary fix for the issue... It is important that you have to delete the file from the dependency and not from my plugin!

**Comment by merdok** [comment]
You have deleted the wrong one, the one from my plugin which you should NOT... I have told you that extra above! You need to delete the correct one.

**Comment by oleg77s** [comment]
Two files found  (pi@homebridge:/var/lib/homebridge $ find /usr/* -name "chuangmi.plug.v1.js") :
1. /usr/local/lib/node_modules/homebridge-miot/lib/modules/outlet/devices/chuangmi.plug.v1.js
2. /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/devices/chuangmi.plug.v1.js

deleted file 2:
[17/10/2021, 10:27:53] ====================
[17/10/2021, 10:27:53] ERROR LOADING PLUGIN homebridge-miot:
[17/10/2021, 10:27:53] Error: Cannot find module './devices/chuangmi.plug.v1'
Require stack:
- /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/models.js
- /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/connectToDevice.js
- /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/discovery.js
- /usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/index.js
- /usr/local/lib/node_modules/homebridge-miot/lib/MiotController.js
- /usr/local/lib/node_modules/homebridge-miot/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-miot/node_modules/miio/lib/models.js:39:22)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[17/10/2021, 10:27:53] ====================
[17/10/2021, 10:27:53] Loading 2 platforms...
[17/10/2021, 10:27:53] [Config] Initializing config platform...
[17/10/2021, 10:27:54] [Config] Running in Service Mode
[17/10/2021, 10:27:54] No plugin was found for the platform "miot" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by oleg77s** [comment]
[17/10/2021, 10:50:39] [miot] [Plug_v1] Connected to device: chuangmi.plug.v1
[17/10/2021, 10:50:39] [miot] [Plug_v1] Creating miot device!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Device Factory - Creating device instance by model: chuangmi.plug.v1!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Initializing device properties
[17/10/2021, 10:50:39] [miot] [Plug_v1] Device properties: [
  "power",
  "usb_power"
]
[17/10/2021, 10:50:39] [miot] [Plug_v1] Initializing device actions
[17/10/2021, 10:50:39] [miot] [Plug_v1] Successfully created a Outlet device! It is a Xiaomi Chuangmi Plug V1.
[17/10/2021, 10:50:39] [miot] [Plug_v1] Initializing accessory!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Accessory Factory - Creating Outlet accessory for device Plug_v1!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Accessory successfully initialized!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Setting up device!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Fetching device info.
[17/10/2021, 10:50:39] [miot] [Plug_v1] Doing device specific setup
[17/10/2021, 10:50:39] [miot] [Plug_v1] Device requires MiCloud! Trying to connect!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Log in to MiCloud cn server with username 1581522456. Request timeout: 5000 milliseconds.
[17/10/2021, 10:50:39] [miot] [Plug_v1] Got device info! Device firmware: 1.2.4_7
[17/10/2021, 10:50:39] [miot] [Plug_v1] MiCloud - Login step 1
[17/10/2021, 10:50:39] [miot] [Plug_v1] MiCloud - Login step 2
[17/10/2021, 10:50:39] [miot] [Plug_v1] MiCloud - Login step 3
[17/10/2021, 10:50:39] [miot] [Plug_v1] MiCloud - Login successful!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Successfully connected to MiCloud!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Doing initial property fetch
[17/10/2021, 10:50:39] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:50:39] [miot] [Plug_v1] Device setup finished! Device ready, you can now control your device!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Getting device info from MiCloud!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Device connected!
[17/10/2021, 10:50:39] [miot] [Plug_v1] Successfully saved device info!
[17/10/2021, 10:50:40] [miot] [Plug_v1] Got device info from MiCloud: 
{
  "did": "11425250",
  "token": "6ac7354a14c15eab50a71c6fea36b7ca",
  "longitude": "37.723221808235",
  "latitude": "55.599789160215",
  "name": "Plug_v1",
  "pid": "0",
  "localip": "192.168.0.239",
  "mac": "F0:B4:29:03:B5:71",
  "ssid": "Apple2",
  "bssid": "F0:B4:29:14:A7:E2",
  "parent_id": "",
  "parent_model": "",
  "show_mode": 1,
  "model": "chuangmi.plug.v1",
  "adminFlag": 1,
  "shareFlag": 0,
  "permitLevel": 16,
  "isOnline": true,
  "desc": "Power plug off | USB on ",
  "extra": {
    "isSetPincode": 0,
    "pincodeType": 0,
    "fw_version": "1.2.4_7",
    "needVerifyCode": 0,
    "isPasswordEncrypt": 0
  },
  "prop": {
    "on": "false",
    "usb_on": "true"
  },
  "uid": 1581522456,
  "pd_id": 14,
  "password": "",
  "p2p_id": "",
  "rssi": -53,
  "family_id": 0,
  "reset_flag": 0
}
[17/10/2021, 10:50:40] [miot] [Plug_v1] Got initial device properties: 
[
  "power: false",
  "usb_power: true"
]
[17/10/2021, 10:50:46] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:50:53] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:51:00] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:51:07] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:51:14] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:51:21] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14
[17/10/2021, 10:51:28] [miot] [Plug_v1] Splitting properties into chunks. Number of chunks: 1. Chunk size: 14

**Comment by oleg77s** [comment]
Ok 👍

**Comment by oleg77s** [comment]
homebridge-miot v0.9.17: 👎

**Comment by merdok** [comment]
I did explain you above that this will not be an easy problem to solve... for now you need to remove the code line like you did before to get it to work!

**Comment by oleg77s** [comment]
line #39 removed👍

**Comment by oleg77s** [comment]
still line #39 must be removed in latest version?

**Comment by merdok** [comment]
Right now yes! I am now preparing an update which will fix it completely but it will take until next year till it is finished since I need to rewrite a lot of code! After that you will not need to remove the line anymore!

**Comment by oleg77s** [comment]
👍 still waiting for...

**Comment by oleg77s** [comment]
Only one power switch, no USB one, shown in homebridge-miot v1.0.4 (v3 is ok)

**Comment by oleg77s** [comment]
in old version usb works:
plug_v1 working now, but main and USB switch on/off together, as in Plug_v3
 
merdok commented [on 17 Oct 2021](https://github.com/merdok/homebridge-miot/issues/91#issuecomment-945073200)
Will adjust that also in the next update.

**Comment by merdok** [comment]
There is no control over the USB in `chuangmi.plug.v1`  https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:outlet:0000A002:chuangmi-v1:2
If there is an USB then it turns on or off with the only one available switch, i cannot change that.

**Comment by oleg77s** [comment]
no, usb don't turned on/off at all, only main switch  (from your plugin)

**Comment by merdok** [comment]
Yes, then this is how that outlet works, there is no usb control for it.

**Comment by oleg77s** [comment]
Mihome utilize Miot too? Strange, there are two switches in Mihome and in old version of your plugin

**Comment by merdok** [comment]
Mi home utilizes probably both the old miio and new miot protocol. I am not sure what you mean with my old plugin showed both since this device was always defined like that as far as I remember. There should be just another switch for the light indicator.

**Comment by oleg77s** [comment]
your old plugin homebridge-miot v0.9.17 with line39 must be removed.
there was main switch, usb switch and led control

**Comment by merdok** [comment]
In version 0.9.17 there was a main switch and usb switch, that you are right, but this seems to had been a mistake because in the miot spec the device only has a main power switch and a indicator light switch.
